### ISSUE TITLE
polyfills  

### ISSUE THREAD

**Issue by rpokrovskij** [tarkhov/postboot#11]
Since you have removed jquery I expect that you use babel polyfills for ES6 and some Node patching polyfills from somelwhere else.  Am I right?

Can you describe you solution related to plyfills in several words? Who is responcible to load them, which should be load  and etc..

**Comment by tarkhov** [comment]
@rpokrovskij Hi, I use Babel to convert the ES6 code into a native javascript, supported by popular browsers, including IE11+.

**Comment by rpokrovskij** [comment]
1) Are babel polyfills included to dist (transpiled code)?
2) what about node patches (as "closest" function, standartazied classList add, remove, toggle etc) - they are not part of babel. are you just not using them?

**Comment by tarkhov** [comment]
@rpokrovskij 
1. I use grunt-babel to convert ES6 code, maybe polyfill in some package dependencies, I don't know.
2. All this features are used in plugins.
