### ISSUE TITLE
Upcoming features

### ISSUE THREAD

**Issue by tarkhov** [tarkhov/postboot#12]
- [x] Card size.
- [x] Card dark style.
- [x] Horizontal collapse. [#17496](https://github.com/twbs/bootstrap/issues/17496)
- [x] Scrolled navbar nav.
- [x] Navbar nav and container horizontal padding fixes `.navbar-container`.
- [x] Replace class like `.font-size-1` to `.fs-1`. - https://github.com/twbs/bootstrap/issues/27365
- [x] Replace `.font-weight-normal` like classes to `.fw-400`.
- [x] Add `.breadcrumb-light` color scheme.
- [x] Sidebar modal.
- [x] Remove too much colors.

**Comment by Fot0n** [comment]
Здравствуйте! Правильно ли понимаю, что вы ни в чём не переопределяете Bootstrap, а только добавляете новые классы? Не хотелось бы что-то сломать, добавив в существующие проекты.

**Comment by tarkhov** [comment]
@Fot0n Совершенно верно, библиотека PostBoot дополняет Bootstrap и ничего не ломает, Вы можете совершенно спокойно использовать их в связке.

**Comment by Fot0n** [comment]
@tarkhov попробовал, реализованное действительно полезно. Звезду поставил — всё чем могу помочь. :-)

**Comment by tarkhov** [comment]
@Fot0n спасибо большое

**Comment by jackttcoms** [comment]
Can i just say amazing! Great work!

**Comment by tarkhov** [comment]
@jackttcoms Thank you very much, it means a lot to me. Don't forget star repository :star:

**Comment by jackttcoms** [comment]
Done 👍 also do you have an eta for the next release? Thanks

**Comment by tarkhov** [comment]
@jackttcoms Thanks, next release will be published in April, I need to complete 4 components.
