### ISSUE TITLE
Цвета

### ISSUE THREAD

**Issue by Fot0n** [tarkhov/postboot#16]
Удаление цветов весьма огорчает. Понятно, что без них библиотека сильно похудела, что здорово, но это была киллер-фича. Возвращать вы их вряд ли будете, форкать и поддерживать, добавляя все последующие изменения кроме этих, сильно не хочется. Недолго длилось счастье. :-( Если всё-таки возможно, обдумайте, пожалуйста, какой-то компромиссный вариант, например, вынос в дополнительный стиль.

**Comment by tarkhov** [comment]
@Fot0n могу вернуть в ближайшее время, не думал, что они так важны

**Comment by Fot0n** [comment]
Ну, я вправе только за себя говорить — мне были полезны. Как и вся библиотека, за что ещё раз спасибо.
