### ISSUE TITLE
Change dropdown-menu size for navbar sizes

### ISSUE THREAD

**Issue by tarkhov** [tarkhov/postboot#84]

**Comment by sptutusukanta** [comment]
Hey @tarkhov,
Why not describe your issues, so one can contribute to your project if you would like.

**Comment by tarkhov** [comment]
> Hey @tarkhov,
> Why not describe your issues, so one can contribute to your project if you would like.

Because no one asks what is not clear on this issue. For this issue, you need to change the size of the drop-down menu when resizing the navbar, for example: `.navbar-1` [navbar size](https://tarkhov.github.io/postboot/#navbar-size) dropdown menu size must be changed to `.dropdown-menu-1` - [dropdown menu size](https://tarkhov.github.io/postboot/#dropdown-menu-size).

**Comment by sptutusukanta** [comment]
Okay...
I think I may look into that soon. :)

**Comment by tarkhov** [comment]
> Okay...
> I think I may look into that soon. :)

Do you need help or advice?

**Comment by tarkhov** [comment]
I added 2 more sizes for the dropdown menu and left the option to change the size of the dropdown menu for any navbar.
